name: "conv3d-baseline"
task_name: "kth"
hidden_dim: None
n_channels: 1,
input_shape: [1, 100, 140]
batch_size: 1
n_epochs: 100
learning_rate: 1e-4
layer_specs:
    - type: conv
      border_mode: [0, 0, 0]
      size: [1, 4, 4]
      num_filters: 32
    - type: pool
      size: [1, 2, 2]
      step: [1, 2, 2]
    - type: conv
      border_mode: [0, 0, 0]
      size: [1, 4, 4]
      num_filters: 32
    - type: pool
      size: [1, 2, 2]
      step: [1, 2, 2]
batch_normalize: True
